#pragma once
#include <HappyAuction/Root.hpp>

namespace HappyAuction
{
    /**/
    enum
    {
        // auction/search
        SCRIPT_HABID,
        SCRIPT_HABUYOUT,
        SCRIPT_HAFILTERBUYOUT,
        SCRIPT_HAFILTERCHAR,
        SCRIPT_HAFILTERLEVEL,
        SCRIPT_HAFILTERRARITY,
        SCRIPT_HAFILTERSTAT,
        SCRIPT_HAFILTERSTATCLEAR,
        SCRIPT_HAFILTERTYPE,
        SCRIPT_HAFILTERUNIQUE,
        SCRIPT_HALISTNEXT,
        SCRIPT_HALISTSELECT,
        SCRIPT_HASEARCH,
        SCRIPT_HASORTBUYOUT,
        SCRIPT_HASORTDPSARMOR,

        // auction/sell
        SCRIPT_HASELL,
        SCRIPT_HASTASHNEXT,
        SCRIPT_HASTASHSELECT,

        // auction/completed
        SCRIPT_HASENDTOSTASH,

        // item
        SCRIPT_HAITEM,
        SCRIPT_HAITEMSTAT,

        // etc
        SCRIPT_HARELOGIN,

        // settings
        SCRIPT_HASETGLOBALDELAY,

        // utilities
        SCRIPT_HAALERT,
        SCRIPT_HABEEP,
        SCRIPT_HALOG,
        SCRIPT_HASLEEP,

        SCRIPT_HAACTIONBID,//DEPRECATED
        SCRIPT_HAACTIONBUYOUT,//DEPRECATED
        SCRIPT_HAACTIONSEARCH,//DEPRECATED
        SCRIPT_HAACTIONSORTDPSARMOR,//DEPRECATED
        SCRIPT_HAACTIONSORTBUYOUT,//DEPRECATED
        SCRIPT_HALISTITEM,//DEPRECATED
        SCRIPT_HALISTITEMSTAT,//DEPRECATED
        SCRIPT_HALISTITEMSOCKET,//DEPRECATED
        SCRIPT_HASTASHSELL,//DEPRECATED
        SCRIPT_HAACTIONRELOGIN,//DEPRECATED
        SCRIPT_HASETTINGSLISTDELAY,//DEPRECATED

        SCRIPT_HATEST,
        SCRIPT_COUNT,
    };
}
 