#pragma once
#include <HappyAuction/Root.hpp>

namespace HappyAuction
{
    /**/
    enum
    {
        SCRIPT_HAFILTERTYPE,
        SCRIPT_HAFILTERLEVEL,
        SCRIPT_HAFILTERRARITY,
        SCRIPT_HAFILTERSTAT,
        SCRIPT_HAFILTERBUYOUT,
        SCRIPT_HAFILTERUNIQUE,

        SCRIPT_HAACTIONBID,
        SCRIPT_HAACTIONBUYOUT,
        SCRIPT_HAACTIONSEARCH,
        SCRIPT_HAACTIONSORTDPSARMOR,
        SCRIPT_HAACTIONSORTBUYOUT,
        SCRIPT_HAACTIONRELOGIN,

        SCRIPT_HALISTSELECT,
        SCRIPT_HALISTNEXT,
        SCRIPT_HALISTITEM,//DEPRECATED
        SCRIPT_HALISTITEMSTAT,//DEPRECATED
        SCRIPT_HALISTITEMSOCKET,//DEPRECATED

        SCRIPT_HASTASHSELL,
        SCRIPT_HASTASHNEXT,

        SCRIPT_HAITEM,
        SCRIPT_HAITEMSTAT,

        SCRIPT_HALOG,
        SCRIPT_HABEEP,
        SCRIPT_HASLEEP,
        SCRIPT_HAALERT,

        SCRIPT_HASETTINGSLISTDELAY,//DEPRECATED
        SCRIPT_HASETGLOBALDELAY,

        SCRIPT_HATEST,

        SCRIPT_COUNT,
    };
}
 